apiVersion: v1
kind: Template
metadata:
  name: jenkins-image-template
parameters:
- name: NAME
  description: "Name of the generated ImageStream and BuildConfig"
  required: true
- name: REPO_NAME
  description: "Name of the repository in GitHub rhoar-ci organization"
  required: true
- name: GITHUB_SECRET
  description: A secret value to use for GitHub webhook URL
  required: true
  generate: expression
  from: "[a-zA-Z0-9]{20}"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: "${NAME}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "${NAME}"
  spec:
    source:
      type: Git
      git:
        uri: "https://github.com/rhoar-ci/${REPO_NAME}"
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        noCache: true
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
    triggers:
    - type: GitHub
      github:
        secret: "${GITHUB_SECRET}"
