apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-master
  spec:
    source:
      type: Git
      git:
        uri: "https://github.com/rhoar-ci/jenkins-master"
        ref: master
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "jenkins:latest"
